### ISSUE TITLE
Notification that i've used the free trial appear, even though i bought the full version. [bug]

### ISSUE THREAD

**Issue by ghost** [noah-nuebling/Mac-Mouse-Fix#1356]
## Description

Whenever i launch my macbook, macos 13.7.5 (22H527), on the newest update of Mac Mouse Fix, i get a notification asking me to pay, even though i paid already. In the app itself, it says i did pay and i can use the software just fine, although, it is annoying that i have to open MMF and turn it back on because the notification makes it disabled. 

## Steps to reproduce

1. Buy Mac Mouse Fix
2. Use it for, i'm assuming minimum 30 days or whatever it is for current free trial to end
3. The notification should appear

## Context

Mac Mouse Fix Version: 3.0.3
macOS Version: 13.7.5 (22H527)
Mouse Model: Logitech m585(but i dont have a problem with the mouse)

## Additional Comments

I have used this software for over a few months already, so it came to me as a surprise that this started happening. i might reinstall it in hopes it fixes the issue, but i dunno what about the license? will the license key work after i reinstall it? or will i have to buy another license for it?

---

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey there @toni20k5267, thanks for your report. I'm sorry about that bug! It should be resolved in the latest [3.0.4](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.4) version of Mac Mouse Fix.

If you'd like a refund, please [click here](https://redirect.macmousefix.com/?message=&target=mmf-apply-for-refund). And If you have any further questions, just let me know.

**Comment by ghost** [comment]
> Hey there [@toni20k5267](https://github.com/toni20k5267), thanks for your report. I'm sorry about that bug! It should be resolved in the latest [3.0.4](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.4) version of Mac Mouse Fix.
> 
> If you'd like a refund, please [click here](https://redirect.macmousefix.com/?message=&target=mmf-apply-for-refund). And If you have any further questions, just let me know.

Thanks a lot! I updated and it works perfectly! And no, I don't want a refund, this software is worth the money for sure. The bug was just a bit annoying anyway, mostly because it needed a connection to start working again. Thank you for fixing the bug!

**Comment by ghost** [comment]
The bug is back! I recently noticed the bug is back, i didnt really use my mac that much before, but the bug is back, acting the same like before. @noah-nuebling

**Comment by noah-nuebling** [comment]
> The bug is back! I recently noticed the bug is back, i didnt really use my mac that much before, but the bug is back, acting the same like before. @noah-nuebling 

Oh I'm sorry about that!

Are you using an Intel Mac? In that case I might have an idea what's causing it

**Comment by ghost** [comment]
Yes, i am using an intel mac, specifically the 2017 macbook pro, the one with that rad touchbar thingy

**Comment by noah-nuebling** [comment]
Hey @toni20k5267, I think I fixed this in the latest [MMF 3.0.5](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.5). Let me know if you're still experiencing issues, and thanks again for your feedback!

**Comment by ghost** [comment]
Well, so far it's working. When I run into any issues, I will let you know. Thanks a lot <3
